/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkersIndexRouteImport } from './routes/dashboard/workers/index'
import { Route as DashboardShiftsIndexRouteImport } from './routes/dashboard/shifts/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkersIndexRoute = DashboardWorkersIndexRouteImport.update({
  id: '/dashboard/workers/',
  path: '/dashboard/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardShiftsIndexRoute = DashboardShiftsIndexRouteImport.update({
  id: '/dashboard/shifts/',
  path: '/dashboard/shifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/dashboard/clients/',
  path: '/dashboard/clients/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/shifts/': typeof DashboardShiftsIndexRoute
  '/dashboard/workers/': typeof DashboardWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/shifts': typeof DashboardShiftsIndexRoute
  '/dashboard/workers': typeof DashboardWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/shifts/': typeof DashboardShiftsIndexRoute
  '/dashboard/workers/': typeof DashboardWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/'
    | '/dashboard/clients/'
    | '/dashboard/shifts/'
    | '/dashboard/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/clients'
    | '/dashboard/shifts'
    | '/dashboard/workers'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/dashboard/'
    | '/dashboard/clients/'
    | '/dashboard/shifts/'
    | '/dashboard/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRoute
  LoginRoute: typeof LoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardShiftsIndexRoute: typeof DashboardShiftsIndexRoute
  DashboardWorkersIndexRoute: typeof DashboardWorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workers/': {
      id: '/dashboard/workers/'
      path: '/dashboard/workers'
      fullPath: '/dashboard/workers/'
      preLoaderRoute: typeof DashboardWorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/shifts/': {
      id: '/dashboard/shifts/'
      path: '/dashboard/shifts'
      fullPath: '/dashboard/shifts/'
      preLoaderRoute: typeof DashboardShiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRoute,
  LoginRoute: LoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardShiftsIndexRoute: DashboardShiftsIndexRoute,
  DashboardWorkersIndexRoute: DashboardWorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
