/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedUpgradeRouteImport } from './routes/_protected/upgrade'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedSettingsTeamRouteImport } from './routes/_protected/settings/team'
import { Route as ProtectedSettingsProfileRouteImport } from './routes/_protected/settings/profile'
import { Route as ProtectedSettingsLegalRouteImport } from './routes/_protected/settings/legal'
import { Route as ProtectedSettingsBillingRouteImport } from './routes/_protected/settings/billing'
import { Route as ProtectedSettingsAgencyRouteImport } from './routes/_protected/settings/agency'
import { Route as ProtectedDashboardWorkersIndexRouteImport } from './routes/_protected/dashboard/workers/index'
import { Route as ProtectedDashboardTimesheetIndexRouteImport } from './routes/_protected/dashboard/timesheet/index'
import { Route as ProtectedDashboardShiftsIndexRouteImport } from './routes/_protected/dashboard/shifts/index'
import { Route as ProtectedDashboardClientsIndexRouteImport } from './routes/_protected/dashboard/clients/index'
import { Route as ProtectedDashboardWorkersWorkerIdRouteImport } from './routes/_protected/dashboard/workers/$workerId'
import { Route as ProtectedDashboardClientsClientIdRouteImport } from './routes/_protected/dashboard/clients/$clientId'
import { Route as ProtectedDashboardWorkersWorkerIdIndexRouteImport } from './routes/_protected/dashboard/workers/$workerId/index'
import { Route as ProtectedDashboardClientsClientIdIndexRouteImport } from './routes/_protected/dashboard/clients/$clientId/index'
import { Route as ProtectedDashboardWorkersWorkerIdLeaveRouteImport } from './routes/_protected/dashboard/workers/$workerId/leave'
import { Route as ProtectedDashboardWorkersWorkerIdEditRouteImport } from './routes/_protected/dashboard/workers/$workerId/edit'
import { Route as ProtectedDashboardWorkersWorkerIdAttendanceRouteImport } from './routes/_protected/dashboard/workers/$workerId/attendance'
import { Route as ProtectedDashboardClientsClientIdNotesRouteImport } from './routes/_protected/dashboard/clients/$clientId/notes'
import { Route as ProtectedDashboardClientsClientIdEditRouteImport } from './routes/_protected/dashboard/clients/$clientId/edit'
import { Route as ProtectedDashboardClientsClientIdCareHoursRouteImport } from './routes/_protected/dashboard/clients/$clientId/care-hours'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUpgradeRoute = ProtectedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsTeamRoute = ProtectedSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsProfileRoute =
  ProtectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsLegalRoute = ProtectedSettingsLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsBillingRoute =
  ProtectedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsAgencyRoute = ProtectedSettingsAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedDashboardWorkersIndexRoute =
  ProtectedDashboardWorkersIndexRouteImport.update({
    id: '/dashboard/workers/',
    path: '/dashboard/workers/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardTimesheetIndexRoute =
  ProtectedDashboardTimesheetIndexRouteImport.update({
    id: '/dashboard/timesheet/',
    path: '/dashboard/timesheet/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardShiftsIndexRoute =
  ProtectedDashboardShiftsIndexRouteImport.update({
    id: '/dashboard/shifts/',
    path: '/dashboard/shifts/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardClientsIndexRoute =
  ProtectedDashboardClientsIndexRouteImport.update({
    id: '/dashboard/clients/',
    path: '/dashboard/clients/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardWorkersWorkerIdRoute =
  ProtectedDashboardWorkersWorkerIdRouteImport.update({
    id: '/dashboard/workers/$workerId',
    path: '/dashboard/workers/$workerId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardClientsClientIdRoute =
  ProtectedDashboardClientsClientIdRouteImport.update({
    id: '/dashboard/clients/$clientId',
    path: '/dashboard/clients/$clientId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardWorkersWorkerIdIndexRoute =
  ProtectedDashboardWorkersWorkerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardWorkersWorkerIdRoute,
  } as any)
const ProtectedDashboardClientsClientIdIndexRoute =
  ProtectedDashboardClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardClientsClientIdRoute,
  } as any)
const ProtectedDashboardWorkersWorkerIdLeaveRoute =
  ProtectedDashboardWorkersWorkerIdLeaveRouteImport.update({
    id: '/leave',
    path: '/leave',
    getParentRoute: () => ProtectedDashboardWorkersWorkerIdRoute,
  } as any)
const ProtectedDashboardWorkersWorkerIdEditRoute =
  ProtectedDashboardWorkersWorkerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedDashboardWorkersWorkerIdRoute,
  } as any)
const ProtectedDashboardWorkersWorkerIdAttendanceRoute =
  ProtectedDashboardWorkersWorkerIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedDashboardWorkersWorkerIdRoute,
  } as any)
const ProtectedDashboardClientsClientIdNotesRoute =
  ProtectedDashboardClientsClientIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => ProtectedDashboardClientsClientIdRoute,
  } as any)
const ProtectedDashboardClientsClientIdEditRoute =
  ProtectedDashboardClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedDashboardClientsClientIdRoute,
  } as any)
const ProtectedDashboardClientsClientIdCareHoursRoute =
  ProtectedDashboardClientsClientIdCareHoursRouteImport.update({
    id: '/care-hours',
    path: '/care-hours',
    getParentRoute: () => ProtectedDashboardClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/upgrade': typeof ProtectedUpgradeRoute
  '/settings/agency': typeof ProtectedSettingsAgencyRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/legal': typeof ProtectedSettingsLegalRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/team': typeof ProtectedSettingsTeamRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/dashboard/clients/$clientId': typeof ProtectedDashboardClientsClientIdRouteWithChildren
  '/dashboard/workers/$workerId': typeof ProtectedDashboardWorkersWorkerIdRouteWithChildren
  '/dashboard/clients/': typeof ProtectedDashboardClientsIndexRoute
  '/dashboard/shifts/': typeof ProtectedDashboardShiftsIndexRoute
  '/dashboard/timesheet/': typeof ProtectedDashboardTimesheetIndexRoute
  '/dashboard/workers/': typeof ProtectedDashboardWorkersIndexRoute
  '/dashboard/clients/$clientId/care-hours': typeof ProtectedDashboardClientsClientIdCareHoursRoute
  '/dashboard/clients/$clientId/edit': typeof ProtectedDashboardClientsClientIdEditRoute
  '/dashboard/clients/$clientId/notes': typeof ProtectedDashboardClientsClientIdNotesRoute
  '/dashboard/workers/$workerId/attendance': typeof ProtectedDashboardWorkersWorkerIdAttendanceRoute
  '/dashboard/workers/$workerId/edit': typeof ProtectedDashboardWorkersWorkerIdEditRoute
  '/dashboard/workers/$workerId/leave': typeof ProtectedDashboardWorkersWorkerIdLeaveRoute
  '/dashboard/clients/$clientId/': typeof ProtectedDashboardClientsClientIdIndexRoute
  '/dashboard/workers/$workerId/': typeof ProtectedDashboardWorkersWorkerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/upgrade': typeof ProtectedUpgradeRoute
  '/settings/agency': typeof ProtectedSettingsAgencyRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/legal': typeof ProtectedSettingsLegalRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/team': typeof ProtectedSettingsTeamRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/dashboard/clients': typeof ProtectedDashboardClientsIndexRoute
  '/dashboard/shifts': typeof ProtectedDashboardShiftsIndexRoute
  '/dashboard/timesheet': typeof ProtectedDashboardTimesheetIndexRoute
  '/dashboard/workers': typeof ProtectedDashboardWorkersIndexRoute
  '/dashboard/clients/$clientId/care-hours': typeof ProtectedDashboardClientsClientIdCareHoursRoute
  '/dashboard/clients/$clientId/edit': typeof ProtectedDashboardClientsClientIdEditRoute
  '/dashboard/clients/$clientId/notes': typeof ProtectedDashboardClientsClientIdNotesRoute
  '/dashboard/workers/$workerId/attendance': typeof ProtectedDashboardWorkersWorkerIdAttendanceRoute
  '/dashboard/workers/$workerId/edit': typeof ProtectedDashboardWorkersWorkerIdEditRoute
  '/dashboard/workers/$workerId/leave': typeof ProtectedDashboardWorkersWorkerIdLeaveRoute
  '/dashboard/clients/$clientId': typeof ProtectedDashboardClientsClientIdIndexRoute
  '/dashboard/workers/$workerId': typeof ProtectedDashboardWorkersWorkerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/upgrade': typeof ProtectedUpgradeRoute
  '/_protected/settings/agency': typeof ProtectedSettingsAgencyRoute
  '/_protected/settings/billing': typeof ProtectedSettingsBillingRoute
  '/_protected/settings/legal': typeof ProtectedSettingsLegalRoute
  '/_protected/settings/profile': typeof ProtectedSettingsProfileRoute
  '/_protected/settings/team': typeof ProtectedSettingsTeamRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/dashboard/clients/$clientId': typeof ProtectedDashboardClientsClientIdRouteWithChildren
  '/_protected/dashboard/workers/$workerId': typeof ProtectedDashboardWorkersWorkerIdRouteWithChildren
  '/_protected/dashboard/clients/': typeof ProtectedDashboardClientsIndexRoute
  '/_protected/dashboard/shifts/': typeof ProtectedDashboardShiftsIndexRoute
  '/_protected/dashboard/timesheet/': typeof ProtectedDashboardTimesheetIndexRoute
  '/_protected/dashboard/workers/': typeof ProtectedDashboardWorkersIndexRoute
  '/_protected/dashboard/clients/$clientId/care-hours': typeof ProtectedDashboardClientsClientIdCareHoursRoute
  '/_protected/dashboard/clients/$clientId/edit': typeof ProtectedDashboardClientsClientIdEditRoute
  '/_protected/dashboard/clients/$clientId/notes': typeof ProtectedDashboardClientsClientIdNotesRoute
  '/_protected/dashboard/workers/$workerId/attendance': typeof ProtectedDashboardWorkersWorkerIdAttendanceRoute
  '/_protected/dashboard/workers/$workerId/edit': typeof ProtectedDashboardWorkersWorkerIdEditRoute
  '/_protected/dashboard/workers/$workerId/leave': typeof ProtectedDashboardWorkersWorkerIdLeaveRoute
  '/_protected/dashboard/clients/$clientId/': typeof ProtectedDashboardClientsClientIdIndexRoute
  '/_protected/dashboard/workers/$workerId/': typeof ProtectedDashboardWorkersWorkerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/accept-terms'
    | '/dpa'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/settings'
    | '/upgrade'
    | '/settings/agency'
    | '/settings/billing'
    | '/settings/legal'
    | '/settings/profile'
    | '/settings/team'
    | '/dashboard/'
    | '/settings/'
    | '/dashboard/clients/$clientId'
    | '/dashboard/workers/$workerId'
    | '/dashboard/clients/'
    | '/dashboard/shifts/'
    | '/dashboard/timesheet/'
    | '/dashboard/workers/'
    | '/dashboard/clients/$clientId/care-hours'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/clients/$clientId/notes'
    | '/dashboard/workers/$workerId/attendance'
    | '/dashboard/workers/$workerId/edit'
    | '/dashboard/workers/$workerId/leave'
    | '/dashboard/clients/$clientId/'
    | '/dashboard/workers/$workerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/accept-terms'
    | '/dpa'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/upgrade'
    | '/settings/agency'
    | '/settings/billing'
    | '/settings/legal'
    | '/settings/profile'
    | '/settings/team'
    | '/dashboard'
    | '/settings'
    | '/dashboard/clients'
    | '/dashboard/shifts'
    | '/dashboard/timesheet'
    | '/dashboard/workers'
    | '/dashboard/clients/$clientId/care-hours'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/clients/$clientId/notes'
    | '/dashboard/workers/$workerId/attendance'
    | '/dashboard/workers/$workerId/edit'
    | '/dashboard/workers/$workerId/leave'
    | '/dashboard/clients/$clientId'
    | '/dashboard/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/accept-invite'
    | '/accept-terms'
    | '/dpa'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/_protected/settings'
    | '/_protected/upgrade'
    | '/_protected/settings/agency'
    | '/_protected/settings/billing'
    | '/_protected/settings/legal'
    | '/_protected/settings/profile'
    | '/_protected/settings/team'
    | '/_protected/dashboard/'
    | '/_protected/settings/'
    | '/_protected/dashboard/clients/$clientId'
    | '/_protected/dashboard/workers/$workerId'
    | '/_protected/dashboard/clients/'
    | '/_protected/dashboard/shifts/'
    | '/_protected/dashboard/timesheet/'
    | '/_protected/dashboard/workers/'
    | '/_protected/dashboard/clients/$clientId/care-hours'
    | '/_protected/dashboard/clients/$clientId/edit'
    | '/_protected/dashboard/clients/$clientId/notes'
    | '/_protected/dashboard/workers/$workerId/attendance'
    | '/_protected/dashboard/workers/$workerId/edit'
    | '/_protected/dashboard/workers/$workerId/leave'
    | '/_protected/dashboard/clients/$clientId/'
    | '/_protected/dashboard/workers/$workerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  DpaRoute: typeof DpaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/upgrade': {
      id: '/_protected/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof ProtectedUpgradeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/team': {
      id: '/_protected/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof ProtectedSettingsTeamRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/profile': {
      id: '/_protected/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedSettingsProfileRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/legal': {
      id: '/_protected/settings/legal'
      path: '/legal'
      fullPath: '/settings/legal'
      preLoaderRoute: typeof ProtectedSettingsLegalRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/billing': {
      id: '/_protected/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof ProtectedSettingsBillingRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/agency': {
      id: '/_protected/settings/agency'
      path: '/agency'
      fullPath: '/settings/agency'
      preLoaderRoute: typeof ProtectedSettingsAgencyRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/dashboard/workers/': {
      id: '/_protected/dashboard/workers/'
      path: '/dashboard/workers'
      fullPath: '/dashboard/workers/'
      preLoaderRoute: typeof ProtectedDashboardWorkersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/timesheet/': {
      id: '/_protected/dashboard/timesheet/'
      path: '/dashboard/timesheet'
      fullPath: '/dashboard/timesheet/'
      preLoaderRoute: typeof ProtectedDashboardTimesheetIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/shifts/': {
      id: '/_protected/dashboard/shifts/'
      path: '/dashboard/shifts'
      fullPath: '/dashboard/shifts/'
      preLoaderRoute: typeof ProtectedDashboardShiftsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/clients/': {
      id: '/_protected/dashboard/clients/'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof ProtectedDashboardClientsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/workers/$workerId': {
      id: '/_protected/dashboard/workers/$workerId'
      path: '/dashboard/workers/$workerId'
      fullPath: '/dashboard/workers/$workerId'
      preLoaderRoute: typeof ProtectedDashboardWorkersWorkerIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/clients/$clientId': {
      id: '/_protected/dashboard/clients/$clientId'
      path: '/dashboard/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof ProtectedDashboardClientsClientIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/workers/$workerId/': {
      id: '/_protected/dashboard/workers/$workerId/'
      path: '/'
      fullPath: '/dashboard/workers/$workerId/'
      preLoaderRoute: typeof ProtectedDashboardWorkersWorkerIdIndexRouteImport
      parentRoute: typeof ProtectedDashboardWorkersWorkerIdRoute
    }
    '/_protected/dashboard/clients/$clientId/': {
      id: '/_protected/dashboard/clients/$clientId/'
      path: '/'
      fullPath: '/dashboard/clients/$clientId/'
      preLoaderRoute: typeof ProtectedDashboardClientsClientIdIndexRouteImport
      parentRoute: typeof ProtectedDashboardClientsClientIdRoute
    }
    '/_protected/dashboard/workers/$workerId/leave': {
      id: '/_protected/dashboard/workers/$workerId/leave'
      path: '/leave'
      fullPath: '/dashboard/workers/$workerId/leave'
      preLoaderRoute: typeof ProtectedDashboardWorkersWorkerIdLeaveRouteImport
      parentRoute: typeof ProtectedDashboardWorkersWorkerIdRoute
    }
    '/_protected/dashboard/workers/$workerId/edit': {
      id: '/_protected/dashboard/workers/$workerId/edit'
      path: '/edit'
      fullPath: '/dashboard/workers/$workerId/edit'
      preLoaderRoute: typeof ProtectedDashboardWorkersWorkerIdEditRouteImport
      parentRoute: typeof ProtectedDashboardWorkersWorkerIdRoute
    }
    '/_protected/dashboard/workers/$workerId/attendance': {
      id: '/_protected/dashboard/workers/$workerId/attendance'
      path: '/attendance'
      fullPath: '/dashboard/workers/$workerId/attendance'
      preLoaderRoute: typeof ProtectedDashboardWorkersWorkerIdAttendanceRouteImport
      parentRoute: typeof ProtectedDashboardWorkersWorkerIdRoute
    }
    '/_protected/dashboard/clients/$clientId/notes': {
      id: '/_protected/dashboard/clients/$clientId/notes'
      path: '/notes'
      fullPath: '/dashboard/clients/$clientId/notes'
      preLoaderRoute: typeof ProtectedDashboardClientsClientIdNotesRouteImport
      parentRoute: typeof ProtectedDashboardClientsClientIdRoute
    }
    '/_protected/dashboard/clients/$clientId/edit': {
      id: '/_protected/dashboard/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/dashboard/clients/$clientId/edit'
      preLoaderRoute: typeof ProtectedDashboardClientsClientIdEditRouteImport
      parentRoute: typeof ProtectedDashboardClientsClientIdRoute
    }
    '/_protected/dashboard/clients/$clientId/care-hours': {
      id: '/_protected/dashboard/clients/$clientId/care-hours'
      path: '/care-hours'
      fullPath: '/dashboard/clients/$clientId/care-hours'
      preLoaderRoute: typeof ProtectedDashboardClientsClientIdCareHoursRouteImport
      parentRoute: typeof ProtectedDashboardClientsClientIdRoute
    }
  }
}

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsAgencyRoute: typeof ProtectedSettingsAgencyRoute
  ProtectedSettingsBillingRoute: typeof ProtectedSettingsBillingRoute
  ProtectedSettingsLegalRoute: typeof ProtectedSettingsLegalRoute
  ProtectedSettingsProfileRoute: typeof ProtectedSettingsProfileRoute
  ProtectedSettingsTeamRoute: typeof ProtectedSettingsTeamRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsAgencyRoute: ProtectedSettingsAgencyRoute,
  ProtectedSettingsBillingRoute: ProtectedSettingsBillingRoute,
  ProtectedSettingsLegalRoute: ProtectedSettingsLegalRoute,
  ProtectedSettingsProfileRoute: ProtectedSettingsProfileRoute,
  ProtectedSettingsTeamRoute: ProtectedSettingsTeamRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedDashboardClientsClientIdRouteChildren {
  ProtectedDashboardClientsClientIdCareHoursRoute: typeof ProtectedDashboardClientsClientIdCareHoursRoute
  ProtectedDashboardClientsClientIdEditRoute: typeof ProtectedDashboardClientsClientIdEditRoute
  ProtectedDashboardClientsClientIdNotesRoute: typeof ProtectedDashboardClientsClientIdNotesRoute
  ProtectedDashboardClientsClientIdIndexRoute: typeof ProtectedDashboardClientsClientIdIndexRoute
}

const ProtectedDashboardClientsClientIdRouteChildren: ProtectedDashboardClientsClientIdRouteChildren =
  {
    ProtectedDashboardClientsClientIdCareHoursRoute:
      ProtectedDashboardClientsClientIdCareHoursRoute,
    ProtectedDashboardClientsClientIdEditRoute:
      ProtectedDashboardClientsClientIdEditRoute,
    ProtectedDashboardClientsClientIdNotesRoute:
      ProtectedDashboardClientsClientIdNotesRoute,
    ProtectedDashboardClientsClientIdIndexRoute:
      ProtectedDashboardClientsClientIdIndexRoute,
  }

const ProtectedDashboardClientsClientIdRouteWithChildren =
  ProtectedDashboardClientsClientIdRoute._addFileChildren(
    ProtectedDashboardClientsClientIdRouteChildren,
  )

interface ProtectedDashboardWorkersWorkerIdRouteChildren {
  ProtectedDashboardWorkersWorkerIdAttendanceRoute: typeof ProtectedDashboardWorkersWorkerIdAttendanceRoute
  ProtectedDashboardWorkersWorkerIdEditRoute: typeof ProtectedDashboardWorkersWorkerIdEditRoute
  ProtectedDashboardWorkersWorkerIdLeaveRoute: typeof ProtectedDashboardWorkersWorkerIdLeaveRoute
  ProtectedDashboardWorkersWorkerIdIndexRoute: typeof ProtectedDashboardWorkersWorkerIdIndexRoute
}

const ProtectedDashboardWorkersWorkerIdRouteChildren: ProtectedDashboardWorkersWorkerIdRouteChildren =
  {
    ProtectedDashboardWorkersWorkerIdAttendanceRoute:
      ProtectedDashboardWorkersWorkerIdAttendanceRoute,
    ProtectedDashboardWorkersWorkerIdEditRoute:
      ProtectedDashboardWorkersWorkerIdEditRoute,
    ProtectedDashboardWorkersWorkerIdLeaveRoute:
      ProtectedDashboardWorkersWorkerIdLeaveRoute,
    ProtectedDashboardWorkersWorkerIdIndexRoute:
      ProtectedDashboardWorkersWorkerIdIndexRoute,
  }

const ProtectedDashboardWorkersWorkerIdRouteWithChildren =
  ProtectedDashboardWorkersWorkerIdRoute._addFileChildren(
    ProtectedDashboardWorkersWorkerIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedUpgradeRoute: typeof ProtectedUpgradeRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardClientsClientIdRoute: typeof ProtectedDashboardClientsClientIdRouteWithChildren
  ProtectedDashboardWorkersWorkerIdRoute: typeof ProtectedDashboardWorkersWorkerIdRouteWithChildren
  ProtectedDashboardClientsIndexRoute: typeof ProtectedDashboardClientsIndexRoute
  ProtectedDashboardShiftsIndexRoute: typeof ProtectedDashboardShiftsIndexRoute
  ProtectedDashboardTimesheetIndexRoute: typeof ProtectedDashboardTimesheetIndexRoute
  ProtectedDashboardWorkersIndexRoute: typeof ProtectedDashboardWorkersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedUpgradeRoute: ProtectedUpgradeRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardClientsClientIdRoute:
    ProtectedDashboardClientsClientIdRouteWithChildren,
  ProtectedDashboardWorkersWorkerIdRoute:
    ProtectedDashboardWorkersWorkerIdRouteWithChildren,
  ProtectedDashboardClientsIndexRoute: ProtectedDashboardClientsIndexRoute,
  ProtectedDashboardShiftsIndexRoute: ProtectedDashboardShiftsIndexRoute,
  ProtectedDashboardTimesheetIndexRoute: ProtectedDashboardTimesheetIndexRoute,
  ProtectedDashboardWorkersIndexRoute: ProtectedDashboardWorkersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  DpaRoute: DpaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
