"""add_client_table

Revision ID: c04750968c35
Revises: 0d579be36366
Create Date: 2026-04-08 17:36:17.778999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04750968c35'
down_revision: Union[str, Sequence[str], None] = '0d579be36366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('assigned_worker_id', sa.UUID(), nullable=True),
    sa.Column('service_type', sa.Enum('personal_care', 'companionship', 'respite', 'nursing', name='servicetype'), nullable=False),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(), nullable=False),
    sa.Column('emergency_contact_relationship', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_hold', 'discharged', name='clientstatus'), nullable=False),
    sa.Column('care_start_date', sa.Date(), nullable=False),
    sa.Column('care_end_date', sa.Date(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['org_members.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
