"""add fields to org_members and create worker_profiles

Revision ID: e7edc0d12631
Revises: 776badc4dc56
Create Date: 2026-04-08 20:23:54.455932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7edc0d12631'
down_revision: Union[str, Sequence[str], None] = '776badc4dc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_profiles',
    sa.Column('org_member_id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'casual', name='employmenttype'), nullable=False),
    sa.Column('has_vehicle', sa.Boolean(), nullable=False),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_member_id'], ['org_members.id'], ),
    sa.PrimaryKeyConstraint('org_member_id')
    )
    op.add_column('org_members', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('org_members', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('org_members', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('org_members', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('org_members', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('org_members', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('org_members', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('org_members', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_members', 'deleted_at')
    op.drop_column('org_members', 'emergency_contact_relationship')
    op.drop_column('org_members', 'emergency_contact_phone')
    op.drop_column('org_members', 'emergency_contact_name')
    op.drop_column('org_members', 'hire_date')
    op.drop_column('org_members', 'date_of_birth')
    op.drop_column('org_members', 'gender')
    op.drop_column('org_members', 'phone_number')
    op.drop_table('worker_profiles')
    # ### end Alembic commands ###
